apiVersion: v1
kind: Pod
metadata:
  name: web-color
spec:
  containers:
    - name: web
      image: kubedevio/web-color:blue
      ports:
        - name: http
          containerPort: 80
          protocol: TCP