apiVersion: apps/v1
kind: Deployment
metadata:
  name: simulador-do-caos
spec:
  replicas: 1
  selector:
    matchLabels:
      app: simulador-do-caos
  template:
    metadata:
      labels:
        app: simulador-do-caos
    spec:
      containers:
      - name: simulador-do-caos
        image: registry.k8s.io/busybox
        command:
          - /bin/sh
        args:
          - -c
          - sleep 60; touch /tmp/health; sleep 600;
        ports:
        - containerPort: 3000
        startupProbe:
            exec:
              command:
                - cat
                - /tmp/health
            failureThreshold: 30 # Número de falhas pra considerar a aplicação não saudável
            periodSeconds: 10 # Intervalo de tempo entre as verificações
---
apiVersion: v1
kind: Service
metadata:
  name: simulador-do-caos
spec:
  selector:
    app: simulador-do-caos
  type: NodePort
  ports:
  - port: 80
    targetPort: 3000
    name: http
    protocol: TCP
    nodePort: 30000