apiVersion: v1
kind: LimitRange
metadata:
  name: min-max-pod
spec:
  limits:
    - type: Pod
      max:
        memory: 512M
        cpu: 250m
      min:
        memory: 250M
        cpu: 100m