apiVersion: v1
kind: PersistentVolume
metadata:
  name: db-pv-nfs
spec:
  capacity:
    storage: 4Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: nfs-static-storage
  nfs:
    server: 192.168.2.166
    path: /mnt/nfs_shared
  mountOptions:
    - nfsvers=4.2