apiVersion: batch/v1
kind: CronJob
metadata:
  name: sorteador-cron
spec:
    schedule: "*/2 * * * * "
    jobTemplate:
      spec:
        ttlSecondsAfterFinished: 60
        completions: 2
        parallelism: 2
        backoffLimit: 10
        template:
          metadata:
            labels:
              app: sorteador
          spec:
            containers:
            - name: sorteador
              image: fabricioveronez/sorteador:v1
              env:
                - name: NUM_ESCOLHIDO
                  value: "2"
                - name: NUM_MAXIMO
                  value: "4"
                - name: DELAY_SORTEIO
                  value: "10"
            restartPolicy: Never
