apiVersion: v1
kind: ServiceAccount
metadata:
  name: kube-board
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: full-access
rules:
- apiGroups: [""]
  resources: ["namespaces"]
  verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: full-access-role
  namespace: default
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list"]
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: kube-board-rolebinding-default
  namespace: default
subjects:
- kind: ServiceAccount
  name: kube-board
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: full-access-role
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kube-board-rolebinding
subjects:
- kind: ServiceAccount
  name: kube-board
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: full-access  
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kube-board
spec:
  selector:
    matchLabels:
      app: kube-board
  template:
    metadata:
      labels:
        app: kube-board
    spec:
      serviceAccount: kube-board
      containers:
      - name: kube-board
        image: fabricioveronez/kube-board:v1
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: kube-board
spec:
  selector:
    app: kube-board
  ports:
  - port: 80
    nodePort: 30000
    targetPort: 3000
  type: NodePort