apiVersion: v1
kind: LimitRange
metadata:
  name: valor-padrao
spec:
  limits:
    - type: Container
      default:
        cpu: 500m
        memory: 64M
      defaultRequest:
        cpu: 250m
        memory: 32M