apiVersion: v1
kind: ResourceQuota
metadata:
  name: contador-objetos
spec:
  hard:
    pods: "4"
    #services: "2"
    #secrets: "3"
    #configmaps: "4"
    #services.loadbalancers: "2"
    #count/deployments.app: "2"
    #count/replicaset.app: "2"